apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prom-role
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
