apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: default
data:
  config.yaml: |
    rules:
    - seriesQuery: 'starlette_request_duration_seconds_bucket'
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      # metricsQuery: (sum(starlette_requests_total{app_name="starlette", status_code="200" }[1m])) by (group_by_label)
      metricsQuery: (avg_over_time(starlette_request_duration_seconds_bucket{app_name="starlette", status_code="200" }[1m])) by (group_by_label)
