version: "3"

services:
  app_db:
    image: mongo
    container_name: app_db
    ports:
      - "27017:27017"
    volumes:
      - db:/app
    restart: unless-stopped
    networks:
      - dhruva-network

  log_db:
    image: mongo
    container_name: log_db
    ports:
      - "27018:27017"
    volumes:
      - db:/log
    restart: unless-stopped
    networks:
      - dhruva-network
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped
    networks:
      - dhruva-network


volumes:
  db: {}
  redis: {}

networks:
  dhruva_network:
    name: dhruva-network
    external: true