version: "3"

services:
  app_db:
    image: bitnami/mongodb:4.2.0
    container_name: app_db
    ports:
      - "27017:27017"
    volumes:
      - db:/app
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USER=$MONGO_APP_DB_USERNAME
      - MONGODB_ROOT_PASSWORD=$MONGO_APP_DB_PASSWORD
    env_file:
      - .env
    networks:
      - dhruva-network


  log_db:
    image: bitnami/mongodb:4.2.0
    container_name: log_db
    ports:
      - "27018:27017"
    volumes:
      - db:/log
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USER=$MONGO_LOG_DB_USERNAME
      - MONGODB_ROOT_PASSWORD=$MONGO_LOG_DB_PASSWORD
    env_file:
      - .env
    networks:
      - dhruva-network
  
  redis:
    image: bitnami/redis:7.0.11
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/bitnami/redis/data
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
    env_file:
      - .env
    networks:
      - dhruva-network

  mongo-admin:
    image: adicom/admin-mongo
    container_name: mongo-admin
    ports:
      - "1234:1234"
    volumes:
      - mongo-admin:/data
    restart: unless-stopped
    environment:
      - PASSWORD=$ADMIN_MONGO_PASSWORD
    env_file:
      - .env
    networks:
      - dhruva-network
    

volumes:
  db: {}
  redis: {}
  mongo-admin: {}

networks:
  dhruva-network:
    name: dhruva-network