version: "3"

services:
  server:
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    working_dir: /src
    ports:
      - "8000:8000"
    volumes:
      - ./server:/src
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    # env_file:
    #   - .env

  client:
    container_name: client
    build:
      context: ./client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/app
    env_file:
      - .env.example

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    expose:
      - 9090
  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3030:3000"
volumes:
  grafana_data: {}
  prometheus_data: {}
