version: "3"

services:
  server:
    container_name: server
    build:
      context: ./server
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - app_data:/server
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    command: uvicorn main:app --workers $BACKEND_WORKERS --port $BACKEND_PORT --host 0.0.0.0 --proxy-headers True
    networks:
      - dhruva-network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    stdin_open: true
    tty: true
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    volumes:
      - ./client:/usr/app
      - app_data:/client
    env_file:
      - .env
    command: yarn start --port $FRONTEND_PORT
    networks:
      - dhruva-network

volumes:
  app_data: {}

networks:
  dhruva-network:
    name: dhruva-network