prometheus:
  url: http://prometheus-kube-prometheus-prometheus.default

rules:
  custom:
    - seriesQuery: '{__name__=~"^starlette_requests$"}'
      resources:
        template: <<.Resource>>
      name:
        matches: ""
        as: "starlette_requests"
      metricsQuery: (starlette_requests[1m])
