apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dhruva-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dhruva-server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: starlette_requests
        target:
          type: AverageValue
          averageValue: "70m"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
