apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dhruva-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dhruva-server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: starlette_request_duration_seconds_count
        target:
          type: AverageValue
          averageValue: 19
