apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 15s
      port: app
      path: /metrics
      scrapeTimeout: 14s
      scheme: http

  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dhruva-server
