{
 "title": "FastApi dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "service", "label": "service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (service, path_template) (rate(starlette_requests_total{namespace=\"$namespace\", service=\"$service\", path_template=~\"/v1/.*\"}[$__interval_sx4]))",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "CPython 3.9.6",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_info{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{implementation}} {{ version }}"
    }
   ]
  },
  {
   "title": "Pod start time ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\", service=\"$service\"} * 1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{namespace=\"$namespace\", service=\"$service\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\"}[$__interval_sx4])) * 100"
    }
   ]
  },
  {
   "title": "Maximum number of open file descriptors",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total count of exceptions raised by path and exception type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (service, path_template, exception_type) (rate(starlette_exceptions_total{namespace=\"$namespace\", service=\"$service\", path_template=~\"/v1/.*\"}[$__interval_sx4]))",
     "legendFormat": "{{path_template}} {{ exception_type }}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{namespace=\"$namespace\", status_code=~\"5..\"}[$__interval_sx4])) by (service, path_template) / sum(rate(starlette_responses_total{namespace=\"$namespace\"}[$__interval_sx4])) by (service, path_template) *100",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Virtual memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resident memory size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Histogram of requests processing time by path (in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_requests_processing_time_seconds_bucket{namespace=\"$namespace\", service=\"$service\"}[5m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(starlette_requests_processing_time_seconds_bucket{namespace=\"$namespace\", service=\"$service\"}[5m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(starlette_requests_processing_time_seconds_bucket{namespace=\"$namespace\", service=\"$service\"}[5m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(starlette_requests_processing_time_seconds_bucket{namespace=\"$namespace\", service=\"$service\"}[5m])) by (le))",
     "legendFormat": "0.1"
    }
   ]
  },
  {
   "title": "Requests currently being processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "starlette_requests_in_progress{namespace=\"$namespace\", service=\"$service\", path_template=~\"/v1/.*\"}",
     "legendFormat": "{{ path_template}}"
    }
   ]
  },
  { "title": "Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Responses total 2xx",
   "type": "timeseries",
   "description": "Total count of responses by method, path and status codes",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{namespace=\"$namespace\", service=\"$service\", status_code=~\"2..\", path_template=~\"/v1/.*\"}[$__interval_sx4])) by (service, status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Responses total 4xx",
   "type": "timeseries",
   "description": "Total count of responses by method, path and status codes",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{namespace=\"$namespace\", service=\"$service\", status_code=~\"4..\", path_template=~\"/v1/.*\"}[$__interval_sx4])) by (service, status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Responses total 5xx",
   "type": "timeseries",
   "description": "Total count of responses by method, path and status codes",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(starlette_responses_total{namespace=\"$namespace\", service=\"$service\", status_code=~\"5..\", path_template=~\"/v1/.*\"}[$__interval_sx4])) by (service, status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "GC objects collected total",
   "type": "timeseries",
   "description": "Objects collected during gc",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(python_gc_objects_collected_total{namespace=\"$namespace\", service=\"$service\",}[$__interval_sx4])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "GC objects uncollectable total",
   "type": "timeseries",
   "description": "Uncollectable object found during GC",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "sum(rate(python_gc_objects_uncollectable_total{namespace=\"$namespace\", service=\"$service\",}[$__interval_sx4])) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "GC collections total",
   "type": "graph",
   "description": "Number of times this generation was collected",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(python_gc_collections_total{namespace=\"$namespace\", service=\"$service\"}[$__interval_sx4])) by (service)",
     "legendFormat": "{{ service  }}"
    }
   ]
  }
 ]
}