{
 "title": "Dhruva Service Specific Dashboard",
 "time": { "from": "2023-02-09T19:20:46.385Z", "to": "2023-02-09T19:25:32.012Z" },
 "templating": {
  "list": [
   { "name": "apiKeyName", "label": "API Key Name" },
   { "name": "userId", "label": "User Id" },
   { "name": "inferenceServiceId", "label": "Inference Service Id" }
  ]
 },
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_requests_total{inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\"}[5m])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dhruva_request_duration_seconds_bucket{inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\"}[5m])) by (le)) or vector(0)"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_requests_total{inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\"}[5m])) OR vector(0)",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Requests Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dhruva_request_duration_seconds_bucket{inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dhruva_request_duration_seconds_bucket{inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dhruva_request_duration_seconds_bucket{inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(dhruva_request_duration_seconds_bucket{inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.1"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_requests_total{status_code!~\"2..\", inference_service=\"$inferenceServiceId\", user_id=\"$userId\", api_key_name=\"$apiKeyName\", status_code!~\"4..\"}[5m])) * 100 / sum(rate(dhruva_requests_total[5m])) OR vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  }
 ]
}