{
 "title": "Dhruva Global Dashboard",
 "time": { "from": "2023-02-09T19:20:46.385Z", "to": "2023-02-09T19:25:32.012Z" },
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_requests_total[5m])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dhruva_request_duration_seconds_bucket[5m])) by (le)) * 1000 OR vector(0)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "All Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_requests_total[5m])) OR vector(0)",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Requests Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dhruva_request_duration_seconds_bucket[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dhruva_request_duration_seconds_bucket[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dhruva_request_duration_seconds_bucket[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(dhruva_request_duration_seconds_bucket[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.1"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(dhruva_requests_total{status_code!~\"2..\"}[5m])) * 100 / sum(rate(dhruva_requests_total[5m]))) OR vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  { "title": "Inference Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_requests_total{inference_service!=\"None\"}[5m])) by(path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dhruva_request_duration_seconds_bucket{inference_service!=\"None\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dhruva_request_duration_seconds_bucket{inference_service!=\"None\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dhruva_request_duration_seconds_bucket{inference_service!=\"None\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(dhruva_request_duration_seconds_bucket{inference_service!=\"None\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.1"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(dhruva_requests_total{status_code!~\"2..\", inference_service!=\"None\"}[5m])) * 100 / sum(rate(dhruva_requests_total{inference_service!=\"None\"}[5m]))) OR vector(0)",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Responses total 2xx",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dhruva_requests_total{status_code=~\"2..\"}) OR vector(0)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Responses total 4xx",
   "type": "stat",
   "description": "Total count of responses by method, path and status codes",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dhruva_requests_total{status_code=~\"4..\"}) OR vector(0)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Responses total 5xx",
   "type": "stat",
   "description": "Total count of responses by method, path and status codes",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dhruva_requests_total{status_code=~\"5..\"}) OR vector(0)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  }
 ]
}