---
##############################
name: Lint and Format Code Base


on:
  push:
    branches-ignore: master

  pull_request:
    branches: master


jobs:
  name: Format Code Base
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,tsx}
  build:

    name: Lint Code Base

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:

          fetch-depth: 0


      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_TSX: true
          VALIDATE_YAML: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}